### ISSUE TITLE
Don't save back on same files when rotating and cropping leaflet and permit undoing

### ISSUE THREAD

**Issue by goatchurchprime** [electionleaflets/electionleaflets#20]
This would mean that the new image would automatically reload in the browser because they'd have a different name.  

The purpose of the undo is to give the staff-editors confidence to fix up leaflets without fear of making mistakes and destroying something permanently.  

The functions that do the editing are rotate_image() crop_image() in apps/leaflets/views.py, which are listed as "hacky".  

Reason for calling them hacky is that they resize and save the different versions (thumbnail, etc) of the image back into the relevant directories, and repeats the code from within apps/leaflets/models.py UploadSession.handle_file_uploads(), when this ought to be a function from within the LeafletImage model.  

The random image filenames of the form "418457ea-55b0-4784-baa7-72df1ed95985.jpg" are coming from the function "update_filename():  return os.path.join(path, str(uuid.uuid4()) + ext)".  [If we used "hashlib.md5(img.tostring()).hexdigest()" we might be able to capture duplicate uploads.]

To make the edits to these images undoable we'll need to add some extra fields into the LeafletImage model, such as image_key_previous, edited_date, edited_staffuser.  Then the leaflet page will trivially be able to show the "last edited", "who by" and "previous picture".  

The undo feature will be crude and won't allow redo.  

Might add other image processing features, such as sharpen, colour balance, etc, depending on the quality of the photos we are consistently getting.

**Comment by symroe** [comment]
This issue was moved to DemocracyClub/electionleaflets#71
