### ISSUE TITLE
Allow uploads of images without filling in all the boxes and distinguish the hidden and pre-marked up states

### ISSUE THREAD

**Issue by goatchurchprime** [electionleaflets/electionleaflets#21]
Probably do this by inserting "email" and "postcode" fields on the mobile-friendly Add leaflet page, and getting rid of the add_leaflet_info() add_step2.html page.  

The user should see that it's in the system immediately (because it's associated to their session), but it won't go onto the main site until it has been marked up.  

We could have a feed of totally new leaflets, but these aren't interesting until they've been categorized and tidied by the office editors.  

The Leaflet.live field is right now a boolean=false and used both for hiding a leaflet and for noting that it is in the uploaded but without details (step2) state.  These are completely different states.  Should add a new field for staff/editor name of who has looked at it.

**Comment by symroe** [comment]
This issue was moved to DemocracyClub/electionleaflets#70
