### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by frabcus** [electionleaflets/electionleaflets#22]
Julian just tried to upload a leaflet to electionleaflet.org from his Samsung Galaxy S5 phone.

Worked well (preview and camera button stuff was good) until hitting submit. Then it paused for ages and said:

*413 Request Entity Too Large*

It's an nginx error message. I think it is the setting `client_max_body_size` which appears to default to 1Mb http://nginx.org/en/docs/http/ngx_http_core_module.html - Julian says the file is about 5Mb.

He reckons you should anyway be downscaling it for fast upload anyway - phones are too high resolution these days. Can you just tell the browser that?

**Comment by frabcus** [comment]
5000 by 3000 pixels is the camera setting!

**Comment by rossjones** [comment]
It's set to *HUGE VALUE* on old site, so it must be the new version you're testing?   I think most of the mobile work is happening at https://github.com/DemocracyClub/electionleaflets
