### ISSUE TITLE
Less confusing "submit and add another" continuation

### ISSUE THREAD

**Issue by goatchurchprime** [electionleaflets/electionleaflets#27]
The response buttons alter between the second, third and fourth pages you "submit" (I would prefer "submit image" rather than the confusing "submit" which I think is short for "submit leaflet").  

The buttons at each stage could simply be [Submit image] and [No more pages].

Also, we can compare this with the Richard's original design which was all uploadable images in a single page, and you filled in between 1 and 8 such file upload boxes, then submitted them in a batch.  (Don't know how this helps, but it sets the workflow in context.)

**Comment by symroe** [comment]
Fixed in https://github.com/DemocracyClub/electionleaflets/commit/21ebc6c415c07fdc2016fc9b8a4770659fa215e5
