### ISSUE TITLE
Election candidate select options improvements 

### ISSUE THREAD

**Issue by goatchurchprime** [electionleaflets/electionleaflets#28]
Candidate names are pulled from the database into a select list, but they make no reference to the party.

1) the final candidate in the list is defaulting to selected.  This is often scrolled off the screen so you don't see it as so.  Very least it should be the top one if one has to be selected, so you can see it's wrong.  

2) Needs to have a party option when the candidate is not listed in the case of:
   (a) a leaflet for a local election candidate (we want those too)
   (b) a leaflet by a non-party organization (eg Young Briton's Foundation)
   (c) a leaflet from the central party that makes no reference to the local candidate.  These are being sent to avoid the campaign spending limits set per constituency and are booked as part of the national spending limit, as are billboard posters that just happen to be in the constituency as well.

**Comment by symroe** [comment]
'Not listed' is now the default.  I'll add party, and I think everything else can be addresses after the leaflet has been uploaded

**Comment by symroe** [comment]
Fixed in https://github.com/DemocracyClub/electionleaflets/commit/710b3f79fadc524e745b547d3691641083555354
